# Generated by Django 5.0.2 on 2024-02-14 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('suscribed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sending_date', models.DateField()),
                ('audience', models.ManyToManyField(to='newsletter.audience')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newsletter.template')),
            ],
        ),
        migrations.CreateModel(
            name='Sent_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newsletter.newsletter')),
                ('suscriptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newsletter.suscriptor')),
            ],
        ),
        migrations.AddField(
            model_name='audience',
            name='suscriptor',
            field=models.ManyToManyField(to='newsletter.suscriptor'),
        ),
    ]
