# Generated by Django 5.0.2 on 2024-02-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='suscribed',
            field=models.BooleanField(default=True),
        ),
    ]
