# Generated by Django 5.0.2 on 2024-02-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='topic',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
