# Generated by Django 5.0.2 on 2024-02-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_category_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='atached_file',
            field=models.FileField(blank=True, null=True, upload_to='attached_files/'),
        ),
    ]
