# Generated by Django 5.0.2 on 2024-02-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_template_atached_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='atached_file',
            new_name='attached_file',
        ),
    ]
